[package]
name = "git-select-branch"
description = "Tiny CLI utility to checkout a recent git branch interactively"
version = "0.1.0"
authors = ["Daniel Ström <D@nielstrom.se>"]
edition = "2018"
license = "MIT OR Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.8.0"
