[package]
name = "git-select-branch"
version = "0.1.0"
authors = ["Daniel Ström <D@nielstrom.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.8.0"
